# Assignment 2

Please submit this assignment as a Jupyter Notebook on Github classroom.

In [4]:
# Import needed packages
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate

## Scalar, Vector, and Matrix Operations

In the following problem, you will translate Homework #1 into Python. 

Begin by filling in the following scalars, vectors, and matrices from Homework #1.

In [5]:
# alpha
a = 6

# beta
b = -1

In [6]:
# u, v, w, are 1-D NumPy arrays
u = np.array([2, 0, -2, 1])
v = np.array([-2, 0, -5, 4])
w = np.array([1, -1, 2, 3])

In [7]:
# x, A, B are 2D NumPy arrays
x = np.array([[3],[-1],[0]])
A = np.array([[2,-1,1],[3,0,4],[0,3,-1]])
B = np.array([[3,2,0],[1,1,2],[-4,0,1]])

**Problem 1a**

In [8]:
 # type in the expression after the 'answer_1a =' in the next line
answer_1a = np.dot(w,u)
print('='*50)
print('Problem 1a')
print("Answer 1a = ", answer_1a)

Problem 1a
Answer 1a =  1


**Problem 1b**

In [9]:
 # type in the expression after the 'answer_1b =' in the next line
answer_1b = np.dot(v,w)
print('-'*50)
print('Problem 1b')
print("Answer 1b = ", answer_1b)

--------------------------------------------------
Problem 1b
Answer 1b =  0


**Problem 1c**

In [12]:
 # type in the expression after the 'result_in_radians =' in the next line
result_in_radians = np.arccos( np.dot(v,w) / (np.linalg.norm(v,2) *np.linalg.norm(w,2)) )

 # convert the result unit from radians to degrees
answer_1c = result_in_radians * 180 / np.pi
print('-'*50)
print('Problem 1c')
print('Answer 1c (degrees) =', answer_1c)

--------------------------------------------------
Problem 1c
Answer 1c (degrees) = 90.0


**Problem 1d**

In [14]:
u = u.reshape((1,4))
v = v.reshape((1,4))
w = w.reshape((1,4))
    
# type in the expression after the 'answer_1d =' in the next line
answer_1d = v.T @ w @ u.T + a * b * w.T

print('-'*50)
print('Problem 1d')
print('Answer 1d = \n', answer_1d)

--------------------------------------------------
Problem 1d
Answer 1d = 
 [[ -8]
 [  6]
 [-17]
 [-14]]


**Problem 1e**

In [15]:
# type in the expression after the 'answer_1e =' in the next line
answer_1e = (B.T @ A) @ x
print('-'*50)
print('Problem 1e')
print('Answer 1e =\n', answer_1e)

--------------------------------------------------
Problem 1e
Answer 1e =
 [[42]
 [23]
 [15]]


**Problem 1f**

In [16]:
# type in the expression after the 'result =' in the next line
answer_1f = (x.T @ A) @ (b*x)
print('-'*50)
print('Problem 1f')
print('Answer 1f = ', answer_1f)

--------------------------------------------------
Problem 1f
Answer 1f =  [[-12]]


**Problem 1g**

In [17]:
# type in the expression after the 'AB =' and 'BA =' in the next line

AB = np.matmul(A,B)
BA = np.matmul(B,A)
print('-'*50)
print('Problem 1g')
print('AB = \n', AB)
print('BA = \n', BA)

--------------------------------------------------
Problem 1g
AB = 
 [[ 1  3 -1]
 [-7  6  4]
 [ 7  3  5]]
BA = 
 [[12 -3 11]
 [ 5  5  3]
 [-8  7 -5]]


**Problem 1h**

In [20]:
# type in the expression after the 'LHS =' and 'RHS' in the next line
LHS =np.matmul((A+B),(A+B))
RHS = A@A + A@B + B@A + B@B
print('-'*50)
print('Problem 1h')
print('LHS = \n', LHS)
print('RHS = \n', RHS)

--------------------------------------------------
Problem 1h
LHS = 
 [[25  9 11]
 [ 0 23 10]
 [-8 -1 14]]
RHS = 
 [[25  9 11]
 [ 0 23 10]
 [-8 -1 14]]


**Problem 1i**

In [39]:
# type in the expression after the 'answer_1i =' in the next line

answer_1i = np.matmul(A, np.identity(3))
print('-'*50)
print('Problem 1i')
print('Answer 1i = \n', answer_1i)
print('='*50)

--------------------------------------------------
Problem 1i
Answer 1i = 
 [[ 2. -1.  1.]
 [ 3.  0.  4.]
 [ 0.  3. -1.]]
